#!/bin/sh
set -eu

# test_checksum_matcher.sh: unit-test the strict POSIX SHA256SUMS matcher
# extracted from install.sh. Every case is a dialect the release workflow can
# emit or that a hostile/mistaken sums file could contain.
#
# Contract: echo the single SHA256 whose filename field is exactly the asset
# name; exit nonzero (no output) for zero matches, no fallback to any other
# line, and no duplicate acceptance.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
INSTALL_SCRIPT="$REPO_ROOT/install.sh"

echo "=== Running strict checksum matcher tests ==="

[ -f "$INSTALL_SCRIPT" ] || { echo "FAIL: install.sh missing" >&2; exit 1; }

TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT INT TERM

sed -n '/^asset_sha_from_sums() {/,/^}/p' "$INSTALL_SCRIPT" > "$TMP/fn.sh"
grep -q '^asset_sha_from_sums() {' "$TMP/fn.sh" || {
  echo "FAIL: could not extract asset_sha_from_sums" >&2
  exit 1
}
tail -n 1 "$TMP/fn.sh" | grep -qx '}' || {
  echo "FAIL: extracted function is not closed" >&2
  exit 1
}

ASSET="grokgod-darwin-arm64"
H1="1111111111111111111111111111111111111111111111111111111111111111"
H2="2222222222222222222222222222222222222222222222222222222222222222"

# Run the extracted matcher in a fresh shell with only the function defined.
run_matcher() {
  sh -c ". '$TMP/fn.sh'; asset_sha_from_sums \"\$1\" \"\$2\"" _ "$1" "$2"
}

expect_accept() {
  label="$1"
  file="$2"
  want="$3"
  if ! got="$(run_matcher "$ASSET" "$file" 2>/dev/null)"; then
    echo "FAIL: $label - rejected an acceptable sums file" >&2
    exit 1
  fi
  if [ "$got" != "$want" ]; then
    echo "FAIL: $label - got '$got', expected '$want'" >&2
    exit 1
  fi
  echo "PASS: accepts $label"
}

expect_reject() {
  label="$1"
  file="$2"
  if got="$(run_matcher "$ASSET" "$file" 2>/dev/null)"; then
    echo "FAIL: $label - accepted with '$got'" >&2
    exit 1
  fi
  echo "PASS: rejects $label"
}

# --- accepted dialects ------------------------------------------------------
printf '%s  %s\n' "$H1" "$ASSET" > "$TMP/plain"
expect_accept "two-space separator" "$TMP/plain" "$H1"

printf '%s *%s\n' "$H1" "$ASSET" > "$TMP/star"
expect_accept "binary '*' marker" "$TMP/star" "$H1"

printf '%s\t%s\n' "$H1" "$ASSET" > "$TMP/tab"
expect_accept "tab separator" "$TMP/tab" "$H1"

printf '%s  %s\r\n' "$H1" "$ASSET" > "$TMP/crlf"
expect_accept "CRLF line ending" "$TMP/crlf" "$H1"

printf '# generated by release\n\n%s  %s\n' "$H1" "$ASSET" > "$TMP/comment"
expect_accept "comment and blank lines" "$TMP/comment" "$H1"

printf '%s  %s   \n' "$H1" "$ASSET" > "$TMP/trailing"
expect_accept "trailing whitespace" "$TMP/trailing" "$H1"

printf '   %s  %s\n' "$H1" "$ASSET" > "$TMP/leading"
expect_accept "leading whitespace" "$TMP/leading" "$H1"

printf '%s  %s\n' "$H1" "$ASSET" > "$TMP/extra"
printf '%s  grokgod-linux-x64\n' "$H2" >> "$TMP/extra"
expect_accept "other platform entries present" "$TMP/extra" "$H1"

printf '%s  %s\n' "ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789" "$ASSET" > "$TMP/upper"
expect_accept "uppercase hex normalized" "$TMP/upper" "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789"

# --- rejected dialects ------------------------------------------------------
printf '%s  %s\n%s  %s\n' "$H1" "$ASSET" "$H1" "$ASSET" > "$TMP/dup"
expect_reject "duplicate identical entries" "$TMP/dup"

printf '%s  %s\n%s  %s\n' "$H1" "$ASSET" "$H2" "$ASSET" > "$TMP/dupdiff"
expect_reject "duplicate entries with different hashes" "$TMP/dupdiff"

printf '%s  grokgod-linux-x64\n' "$H1" > "$TMP/missing"
expect_reject "missing entry (no first-line fallback)" "$TMP/missing"

: > "$TMP/empty"
expect_reject "empty sums file" "$TMP/empty"

printf '%s  %s.bak\n' "$H1" "$ASSET" > "$TMP/suffix"
expect_reject "suffix near-match" "$TMP/suffix"

printf '%s  prefix-%s\n' "$H1" "$ASSET" > "$TMP/prefix"
expect_reject "prefix near-match" "$TMP/prefix"

printf '%s  assets/%s\n' "$H1" "$ASSET" > "$TMP/pathqual"
expect_reject "path-qualified name" "$TMP/pathqual"

printf '%s  %s extra\n' "$H1" "$ASSET" > "$TMP/three"
expect_reject "three fields" "$TMP/three"

printf '%s  %s\n' "zzzznotahash" "$ASSET" > "$TMP/nonhex"
expect_reject "non-hex hash" "$TMP/nonhex"

printf '%s  %s\n' "111111111111111111111111111111111111111111111111111111111111111" "$ASSET" > "$TMP/short"
expect_reject "short hash" "$TMP/short"

printf '%s  %s\n' "${H1}0" "$ASSET" > "$TMP/long"
expect_reject "long hash" "$TMP/long"

printf '%s *%s\n' "$H1" "$ASSET" > "$TMP/starhash2"
expect_accept "single space before star name" "$TMP/starhash2" "$H1"
printf '%s  *%s\n' "$H1" "$ASSET" > "$TMP/starname"
expect_accept "star before name" "$TMP/starname" "$H1"

# NUL bytes: BSD awk truncates records at NUL, so a NUL-joined duplicate can
# hide a second entry from the match counter. Must fail closed.
printf '%s  %s\000%s  %s\n' "$H1" "$ASSET" "$H1" "$ASSET" > "$TMP/nul"
expect_reject "NUL-joined duplicate entry" "$TMP/nul"

if [ -n "$(printf 'a\000b' | tr -d '\000')" ]; then
  echo "PASS: NUL detection primitives available"
fi

echo "=== Strict checksum matcher tests passed ==="
